# Copyright (c) 2020 Timothy Brackett
# Licensed under the MIT license

image: gcc

build:
    stage: build

    before_script:
        - 'apt-get update && apt-get install -y cmake cmake-data libncurses-dev libvterm-dev doxygen graphviz'

    script:
        - 'mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE:String=Release && make'

build_test:
    stage: test

    before_script:
        - 'apt-get update && apt-get install -y cmake cmake-data curl libncurses-dev libvterm-dev doxygen graphviz'

    script:
        - 'mkdir build_test && cd build_test && cmake .. -DCMAKE_BUILD_TYPE:String=Debug -DNCPTY_TEST:Bool=ON && make && make test && make coverage && find .. -name \*.gcov'
        - 'find .. -name \*.gcov'

    after_script:
        - 'bash <(curl -s https://codecov.io/bash) -t ca4ecbd3-76f2-420b-9f67-3e915679df5c -f *.gcov -p $(pwd)'

    artifacts:
        untracked: true
        paths:
            - '*.gcov'
