# Copyright (c) 2020 Timothy Brackett
# Licensed under the MIT license

before_script:
    - 'apt-get update && apt-get install -y cmake cmake-data curl libncurses-dev libvterm-dev doxygen graphviz tmux valgrind'

include:
    - template: SAST.gitlab-ci.yml

build:
    image: gcc:latest
    stage: build

    script:
        - 'git submodule init && git submodule update && mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE:String=Release -DBUILD_TESTING:Bool=OFF && make'

build_test:
    image: gcc:latest
    stage: test

    script:
        - 'git submodule init && git submodule update && mkdir build_test && cd build_test && cmake .. -DCMAKE_BUILD_TYPE:String=Debug -DTEST_COVERAGE:Bool=ON && make && ../run_in_tmux.sh ctest --schedule-random && make coverage'

    after_script:
        - 'apt-get install -y python3-pip && pip install cpp-coveralls && coveralls --exclude src/test --exclude build_test --gcov-options "\-lp"'
        - 'apt-get install -y gcovr && gcovr --xml-pretty -o coverage.xml --root .'

    artifacts:
      name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
      expire_in: 365 days
      reports:
        coverage_report:
          coverage_format: cobertura
          path: coverage.xml

memcheck:
    image: gcc:latest
    stage: test
    when: manual
    script:
        - 'git submodule init && git submodule update && mkdir leak_test && cd leak_test && cmake ../ -DCMAKE_BUILD_TYPE:String=Debug -DUSE_INTERNAL_NCURSES_BUILD:Bool=ON && make && cmake . && make && ../run_in_tmux.sh ctest --schedule-random -L memcheck -D ExperimentalMemCheck && cat Testing/Temporary/MemoryChecker.*.log && [ $(cat Testing/Temporary/MemoryChecker.*.log | wc -l) == "0" ]'

coverity:
    image: registry.gitlab.com/bracketttc/ncpty/coverity:latest
    stage: test

    script:
        - 'mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE:String=Release -DBUILD_TESTING:Bool=OFF && cov-build --dir cov-int make && tar -jcf ncpty.tbz cov-int'

    after_script:
        - 'cd build && curl --form token=${COVERITY_TOKEN} --form email=brackett.tc@gmail.com --form file=@ncpty.tbz --form version=$(grep CMAKE_PROJECT_VERSION:STATIC  -r | cut -d = -f 2 | tail -n 1)-$(git rev-parse --short=8 HEAD) --form description="" https://scan.coverity.com/builds?project=bracketttc%2Fncpty'
